---

- stat:
    path: "{{oracle_home}}"
  sudo: true
  sudo_user: "{{oracle_user}}"
  register: ms_start_oracle_home_stat_result

- name: Main MS Start Task
  include: ms_start_main.yml
  when: ms_start_oracle_home_stat_result.stat.exists
