---
#Apply PSU patches
- name: Template patch list
  sudo: true
  sudo_user: "{{oracle_user}}"
  template:
    src: quarterly_patch_list.j2
    dest: "{{ oracle_stage_install }}/patch_list_{{ oracle_version }}_{{ patch_name }}.txt"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
  #when: quarterly_patches[oracle_version] is defined

- name: Opatch prereq check for PSU patches
  sudo: true
  sudo_user: "{{oracle_user}}"
  shell: opatch prereq CheckConflictAgainstOHWithDetail -phBaseFile {{ oracle_stage_install }}/patch_list_{{ oracle_version }}_{{ patch_name }}.txt
  environment: "{{ env }}"
  register: conflicts_psu
  #when: quarterly_patches[oracle_version] is defined
  async: 900
  poll: 20

- debug: var=conflicts_psu.rc
  tags: debug

- name: Apply PSU patches
  sudo: true
  sudo_user: "{{oracle_user}}"
  shell: opatch napply -force -silent -skip_subset -skip_duplicate -phBaseFile {{ oracle_stage_install }}/patch_list_{{ oracle_version }}_{{ patch_name }}.txt
  environment: "{{ env }}"
  register: apply_psu
  #when: quarterly_patches[oracle_version] is defined
  async: 1200 
  poll: 60

- debug: var=apply_psu.rc
  tags: debug
