---

- stat:
    path: "{{oracle_home}}"
  sudo: true
  sudo_user: "{{oracle_user}}"
  register: admin_stop_oracle_home_stat_result

- name: Stop Admin Main Task
  include: stop_admin_main.yml
  when: admin_stop_oracle_home_stat_result.stat.exists
