---

- stat:
    path: "{{oracle_home}}"
  sudo: true
  sudo_user: "{{oracle_user}}"
  register: nm_start_oracle_home_stat_result

- name: Start Node Manager Task
  include: start_nm.yml
  when: nm_start_oracle_home_stat_result.stat.exists
  tags: start_nm

