---

- stat:
    path: "{{oracle_home}}"
  sudo: true
  sudo_user: "{{oracle_user}}"
  register: wlst_oracle_home_stat_result

- debug: var=wlst_oracle_home_stat_result.stat.exists

- name: Main WLST Task
  include: wlst_main.yml
  when: wlst_oracle_home_stat_result.stat.exists
