---

- stat:
    path: "{{oracle_home}}"
  sudo: true
  sudo_user: "{{oracle_user}}"
  register: ms_stop_oracle_home_stat_result

- name: Main MS STOP Task
  include: ms_stop_main.yml
  when: ms_stop_oracle_home_stat_result.stat.exists
