---

- stat:
    path: "{{oracle_home}}"
  sudo: true
  sudo_user: "{{oracle_user}}"
  register: admin_start_oracle_home_stat_result

- name: Start Admin Main Task
  include: start_admin_main.yml
  when: admin_start_oracle_home_stat_result.stat.exists
