---

- set_fact:
    pega_log_home: /x/web/gops/{{domain_name}}/logs

- set_fact: 
    start_admin_command: "nohup {{ domain_home }}/{{ domain_name }}/bin/startWebLogic.sh > {{ pega_log_home }}/admin_{{ today }}.log &"

- debug: var=start_admin_command
  tags: debug

- name: Check if admin port is listening
  wait_for:
    host: "{{ansible_hostname}}"
    port: "{{ admin_listen_port }}"
    delay: 0
    timeout: 3
  register: port_check
  ignore_errors: yes

- debug: var=port_check
  tags: debug

- name: start admin server
  sudo: true
  sudo_user: "{{oracle_user}}"
  shell: "{{start_admin_command}}" 
  when: (port_check.failed is defined and port_check.failed|upper == "TRUE") or (port_check.state is defined and port_check.state|upper != "STARTED")

- wait_for:
    host: "{{ansible_hostname}}"
    port: "{{admin_listen_port}}"
    timeout: 150
